/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { PrismaService } from "../../prisma/prisma.service";
import { Prisma, Route as PrismaRoute } from "@prisma/client";
import { Route } from "./Route";

export class RouteServiceBase {
  constructor(protected readonly prisma: PrismaService) {}

  async count(args: Omit<Prisma.RouteCountArgs, "select">): Promise<number> {
    return this.prisma.route.count(args);
  }

  async routes<T extends Prisma.RouteFindManyArgs>(
    args: Prisma.SelectSubset<T, Prisma.RouteFindManyArgs>
  ): Promise<PrismaRoute[]> {
    return this.prisma.route.findMany<Prisma.RouteFindManyArgs>(args);
  }
  async route<T extends Prisma.RouteFindUniqueArgs>(
    args: Prisma.SelectSubset<T, Prisma.RouteFindUniqueArgs>
  ): Promise<PrismaRoute | null> {
    return this.prisma.route.findUnique(args);
  }
  async createRoute<T extends Prisma.RouteCreateArgs>(
    args: Prisma.SelectSubset<T, Prisma.RouteCreateArgs>
  ): Promise<PrismaRoute> {
    return this.prisma.route.create<T>(args);
  }
  async updateRoute<T extends Prisma.RouteUpdateArgs>(
    args: Prisma.SelectSubset<T, Prisma.RouteUpdateArgs>
  ): Promise<PrismaRoute> {
    return this.prisma.route.update<T>(args);
  }
  async deleteRoute<T extends Prisma.RouteDeleteArgs>(
    args: Prisma.SelectSubset<T, Prisma.RouteDeleteArgs>
  ): Promise<PrismaRoute> {
    return this.prisma.route.delete(args);
  }
  async CreateRoute(args: Route): Promise<Route> {
    throw new Error("Not implemented");
  }
}
